### ISSUE TITLE
하루 우라라, 후완다리즈 몬스터 영한 사전 오기재 수정

### ISSUE THREAD

**Issue by tpdns90321** [tiredhermitcrab/YGOSmallWorldMap#2]
하루 우라라와 후완다리즈 몬스터들의 영어 이름이 잘못 기재되어 있어서 사용할 수 없는 문제가 있습니다.

해당 문제를 해결해서 올립니다. 

#1

**Comment by tiredhermitcrab** [comment]
한-영 변환쪽 출처를 바꿨더니 문제가 발생했네요. 다른 카드들도 오류가 좀 있어서 통일해 놓겠습니다.
